import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Head from "next/head";


export const metadata: Metadata = {
  title: "C++",
  description: "Generated by create next app",
  icons:{
    icon:"/logo.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Head>
      {/*<link rel="icon" href={"/logo.svg"}/>*/}
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={"use-credentials"}/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
              rel="stylesheet"/>
    </Head>
    <body>
    {children}
    </body>
    </html>
  );
}
